config/routes.rb
Rails.application.routes.draw do
  resources :foods

  root 'foods#index'

end

app/models/food.rb
class Food < ActiveRecord::Base
  has_many :ingredients, dependent: :destroy

  # Ingredients ignored unless they have both a name and a quantity
  accepts_nested_attributes_for :ingredients, 
    reject_if: proc { |ingredient| ingredient[:name].blank? || ingredient[:quantity].blank? },
    allow_destroy: true

  validates :name, presence: true

  def self.matching( search_string )
    return Food.all.order(created_at: :desc).select do |f| 
      search_array = search_string.split(',').map(&:strip)
      whitelist = search_array.select { |elem| elem =~ /\A[^\-].*/ } # only elements that don't start with a dash
      blacklist = search_array.select { |elem| elem =~ /\A\-.*/ } # only elements that start with a dash

      blacklist.map { |elem| elem.slice!(0) } # remove leading dash on each item

      f.matches_tags_or_ingredients?(whitelist) && f.passes_blacklist?(blacklist)
    end
  end

  def tag_array
    return [] if tags.nil? || tags.empty?
    tags.split(',').map(&:strip) # remove leading & trailing spaces after split
  end


  def can_make_without?( missing_ingredients )
    return true if missing_ingredients.nil?

    # Ensure that wrong case doesn't prevent a match
    lowercase_missing_ingredients = missing_ingredients.map(&:downcase)

    ingredients.each do |ingredient|
      return false if lowercase_missing_ingredients.include? ingredient.name.downcase
    end
    true # Recipe doesn't use the missing ingredients 
  end


  def passes_tags_blacklist?( blacklist )
    return true if blacklist.nil? || tags.nil?

    # Ensure that wrong case doesn't prevent a match
    lowercase_blacklist = blacklist.map(&:downcase)
    tag_array.each do |tag|
      return false if lowercase_blacklist.include? tag.downcase
    end
    true # Recipe tags don't include blacklist items
  end


  def passes_blacklist?( blacklist )
    can_make_without?( blacklist ) && passes_tags_blacklist?( blacklist )
  end


  def matches_ingredient?( search_ingredient )
    return true if search_ingredient.nil? || search_ingredient.empty?

    ingredients.each do |ingredient|
      return true if ingredient.name.downcase.include? search_ingredient.downcase
    end
    false # Recipe ingredients don't include the search term
  end


  def matches_tags?( search )
    return true if search.nil? || search.empty?

    tag_array.each do |tag|
      return true if tag.downcase.include? search.downcase
    end
    false # Recipe tags don't include the search term
  end


  def matches_tags_or_ingredients?( search_array )
    return true if search_array.nil? || search_array.empty?

    search_array.each do |search|
      return false unless matches_ingredient?(search) || matches_tags?(search)
    end
    true # All search terms were matched
  end



  #  -- NOTE FOR FUTURE FUNCTIONALITY
  # 
  # In future revisions of the recipe tracker, the user will be able to
  # record when they have made the recipe, and record how awesome the 
  # recipe was (on a scale of 1-5). The user would then be able to sort
  # retrieved recipes by when it was last made, by total achieved awesome-
  # ness, or by average awesomeness.
  #
  #    def last_made
  #      # Not done
  #    end
  #
  #    def number_of_times_made
  #      # Not done
  #    end
  #
  #    def average_awesomeness
  #      # Not done
  #    end 
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :food

  validates :name, presence: true
  validates :quantity, presence: true

  def metrics 
    %w{
      bunch
      cup
      fl-oz
      gallon
      gram
      lb
      liter
      ml
      oz
      pinch
      pint
      quart
      tbsp
      tsp
    }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    if params[:search] 
      @foods = Food.matching( params[:search] )
      @search = params[:search]
    else 
      @foods = Food.all.order(created_at: :desc)
    end
  end
  
  def new
    @food = Food.new
  end

  def show
    @food = Food.find(params[:id])
  end

  def edit
    @food = Food.find(params[:id])
  end

  def create 
    @food = Food.new( food_params )

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Recipe was successfully created.' }
      else
        format.html { render 'new' }
      end
    end
  end

  def update 
    @food = Food.find( params[:id] )

    respond_to do |format|
      if @food.update!( food_params )
        format.html { redirect_to @food, notice: 'Recipe was successfully updated.' }
      else
        format.html { render 'edit' }
      end
    end
  end

  def destroy
    @food = Food.find( params[:id] )

    respond_to do |format|
      if @food.destroy
        format.html { redirect_to foods_url, notice: 'Recipe was successfully updated.' }
      else
        format.html { redirect_to @food, alert: 'Unable to delete food.' }
      end
    end 
  end

  private
  # Using a private method to encapsulate the permissible parameters is just a good pattern
  # since you'll be able to reuse the same permit list between create and update. Also, you
  # can specialize this method with per-user checking of permissible attributes.
  def food_params
    params.require(:food).permit(:name, :author, :source, :haley_comment, :tags, :content, ingredients_attributes: [ :id, :name, :quantity, :metric, :_destroy ] )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/foods/_form.html.erb
<%= simple_form_for @food do |f| %>
  <%= f.input :name, label: "What it's called" %>
  <div class="row">
    <div class="medium-4 columns">
      <%= f.input :author, label: "Who made it up" %>
    </div>
    <div class="medium-8 columns">
      <div class="row collapse">
        <label>Where you found it</label>
        <div class="small-2 large-2 columns">
          <span class="prefix">http://</span>
        </div>
        <div class="small-10 large-10 columns">
          <%= f.input_field :source, placeholder: "Enter your URL..." %>
        </div>
      </div>
    </div>
  </div>

  <%= f.input :haley_comment, label: "What Haley thinks about it" %>
  <%= f.input :tags %>

  <h3>Ingredients</h3>
  <div id="ingredients">
    <%= f.simple_fields_for :ingredients do |i| %>
      <%= render 'ingredient_fields', f: i %>
    <% end %>
    <div class="links">
      <%= link_to_add_association raw('<span class="add-icon"><i class="fa fa-plus-square-o fa-lg"></i></span> Add Ingredient'), f, :ingredients %>
    </div>
  </div>

  <br>
  <h3>Instructions</h3>
  <%= f.input :content %>
  <%= f.button :submit, "Save Recipe" %>
<% end %>

app/views/foods/_ingredient_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="small-6 columns">
      <%= f.input :name, label: "What it is" %>
    </div>
    <div class="small-5 columns">
      <div class="row collapse">
        <label>* How much</label>
        <div class="small-7 columns">
          <%= f.input_field :quantity %>
        </div>
        <div class="small-5 columns">
          <span class="postfix">
            <%= f.input_field :metric, collection: f.object.metrics %>
          </span>
        </div>
      </div>
    </div>
    <div class="small-1 columns">
      <%= link_to_remove_association raw('<div class="remove-icon"><i class="fa fa-minus-square fa-lg"></i></div>'), f %>  
    </div>
  </div>
</div>

app/views/foods/edit.html.erb
<div class="new-recipe-banner">
  <div class="row">
    <div class="small-10 small-offset-1 medium-6 medium-offset-3 large-4 large-offset-4 columns">
      <div class="search-summary text-center">
        <h1><span class="cutlery-icon"><i class="fa fa-cutlery"></i></span>Edit Recipe</h1> 
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-12 medium-8 medium-offset-2 columns">
    <%= render "form" %>
  </div>
</div>

app/views/foods/index.html.erb
<div class="index-banner <%= "searching" unless @search.nil? %>">
  <div class="row">
    <div class="small-10 small-offset-1 medium-6 medium-offset-3 large-4 large-offset-4 columns">
      <div class="search-summary text-center">
        <% if @search.nil? %>
          <h2 class="sub-header">Let's find some recipes!</h2> 
        <% else %>
          <h4 class="sub-header">You searched for <strong><%= "#{ @search.html_safe }"%></strong>, which returned <strong><%= "#{@foods.size}"%> </strong> <%= "#{'result'.pluralize(@foods.size)}!" %></strong></h4> 
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row index-wrapper">
  <div class="small-12 columns">
    <div class="row">
      <% @foods.each_with_index do |food, index| %>
        <% num_columns = case index
            when 0..1 then 6
            when 2..4 then 4
            else 3 
            end %>
        <div class="recipe-unit small-12 medium-<%= num_columns %> columns">
          <%= link_to image_tag('food.jpg', class: 'recipe-img' ), food %>
          <div class="recipe-name text-center">
            <%= link_to food.name, food %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/foods/new.html.erb
<div class="new-recipe-banner">
  <div class="row">
    <div class="small-10 small-offset-1 medium-6 medium-offset-3 large-4 large-offset-4 columns">
      <div class="search-summary text-center">
        <h1><span class="cutlery-icon"><i class="fa fa-cutlery"></i></span>New Recipe</h1> 
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-12 medium-8 medium-offset-2 columns">
    <%= render "form" %>
  </div>
</div>

app/views/foods/show.html.erb
<div class="show-recipe-banner">
  <div class="row">
    <div class="small-10 small-offset-1 medium-6 medium-offset-3 large-4 large-offset-4 columns">
      <div class="search-summary text-center">
        <h2><%= @food.name %></h2> 
      </div>
    </div>
  </div>
  <div class="row">
    <div class="byline small-10 small-offset-1 columns">
      <% unless @food.source.blank? && @food.author.blank? %>
        <% unless @food.author.blank? %>
          <div class="author">
            <%= "by #{@food.author} " %>
            <% unless @food.source.blank? %>
              <%= " - " %>
              <%= link_to( "(Link to Original)", "http://"+@food.source ) %>
            <% end %> 
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="small-10 small-offset-1 columns">
      <div class="tags">
        <ul class="inline-list">
          <% @food.tag_array.each do |tag| %>
            <li class="tag">
              <span class="info radius label"><%= "#{tag}" %></span>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <div class="row">
      <div class="small-12 medium-6 large-3 columns">
        <div class="recipe-details">
          <ul class="inline-list">
            <li><%= link_to 'Edit', edit_food_path(@food), class: "secondary button tiny" %></li>
            <li><%= link_to 'Delete', @food, method: :delete, data: { confirm: 'Are you sure?' }, class: "alert button tiny" %></li>
          </ul>
          <div class="haley-comment">
            <% unless @food.haley_comment.blank? %>
              <blockquote><%= "#{@food.haley_comment}" %><cite>Haley Tucker</cite></blockquote>
            <% end %>
          </div>
        </div>
      </div>
      <div class="small-12 medium-6 large-3 columns">
        <% unless @food.ingredients.empty? %>
          <div class="recipe-ingredients">
            <h3 class="subheader">Ingredients</h3>
            <ul class="ingredients">
              <% @food.ingredients.each do |ingredient| %>
                <li>
                  <span class="qty">
                    <%= "#{ingredient.quantity} " %>
                    <%= "#{ ingredient.metric } of " unless ingredient.metric.nil? %>
                  </span>
                  <span class="ingredient-name">
                     <%= "#{ingredient.name}" %>
                  </span>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
      <div class="small-12 large-6 columns">
        <div class="recipe-content">
          <h3 class="subheader">Instructions</h3>  
          <%= simple_format @food.content %>        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Recipe!" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Recipe!", foods_path %></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li class="active"><%= link_to "New Recipe", new_food_path %></li>
        </ul>

        <!-- Left Nav Section -->
        <ul class="left">
          <li class="has-form">
            <form action=<%= foods_path %> >
              <div class="row collapse">
                <div class="small-9 columns">
                  <input type="text" name="search" placeholder="Find Stuff">
                </div>
                <div class="small-3 columns">
                  <button class="info button expand">Search</button>
                </div>
              </div>
            </form>
          </li>
        </ul>
      </section>
    </nav>
    <%= yield %>
    <%= javascript_include_tag "application" %>    
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag :cocoon %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>